services:
  web_backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ${DATA_IMAGES}:/app/data/images
      - ${DATA_DUMPS}:/app/data/dumps